// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqaJUD_ZYVJzRhdtViSn2tqyJp1AwWQdo',
    appId: '1:323123164675:web:ccb287a39f78215cc50036',
    messagingSenderId: '323123164675',
    projectId: 'apimap-1105a',
    authDomain: 'apimap-1105a.firebaseapp.com',
    storageBucket: 'apimap-1105a.appspot.com',
    measurementId: 'G-0GQHSXLCTP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpRuw_j5mSAX3oUGVfOYFp_Y7ZMlBrXAM',
    appId: '1:323123164675:android:40d881c5b73b6b70c50036',
    messagingSenderId: '323123164675',
    projectId: 'apimap-1105a',
    storageBucket: 'apimap-1105a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeecN1wtzGQCxLutGo8FAK-69wZiiWFPw',
    appId: '1:323123164675:ios:4d70eb1cef0f1638c50036',
    messagingSenderId: '323123164675',
    projectId: 'apimap-1105a',
    storageBucket: 'apimap-1105a.appspot.com',
    iosClientId: '323123164675-vd1r5j5laqi0jcnobhuammgp9p1qqlig.apps.googleusercontent.com',
    iosBundleId: 'vn.vietmap.vmnavi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeecN1wtzGQCxLutGo8FAK-69wZiiWFPw',
    appId: '1:323123164675:ios:566b0b37c5a54c33c50036',
    messagingSenderId: '323123164675',
    projectId: 'apimap-1105a',
    storageBucket: 'apimap-1105a.appspot.com',
    iosClientId: '323123164675-bt3a9t5otqk85jmasfemd59ckiao221i.apps.googleusercontent.com',
    iosBundleId: 'vn.vietmap.vietmapMap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqaJUD_ZYVJzRhdtViSn2tqyJp1AwWQdo',
    appId: '1:323123164675:web:e68d337f4b988c79c50036',
    messagingSenderId: '323123164675',
    projectId: 'apimap-1105a',
    authDomain: 'apimap-1105a.firebaseapp.com',
    storageBucket: 'apimap-1105a.appspot.com',
    measurementId: 'G-ZNH0607W5Q',
  );
}
